### ISSUE TITLE
Memory consumption increases indefinitely over time

### ISSUE THREAD

**Issue by zazabe** [faern/triggered#1]
If the `Listener` is used to stop a stream with [`take_until`](https://docs.rs/futures/0.3.14/futures/stream/trait.StreamExt.html#method.take_until), the memory is growing indefinitely because a new `Waker` is added to the shared `Vec<Waker>` every time, see: https://github.com/faern/triggered/blob/v0.1.1/src/lib.rs#L236.

![triggered-valgrind](https://user-images.githubusercontent.com/401598/114362422-99e0eb80-9b77-11eb-8b89-deb2fe04082b.png)

**Comment by zazabe** [comment]
we switched to [GenericManualResetEvent](https://docs.rs/futures-intrusive/0.4.0/futures_intrusive/sync/struct.GenericManualResetEvent.html) from [futures-intrusive](https://docs.rs/futures-intrusive/0.4.0), which doesn't suffer from this issue.

**Comment by faern** [comment]
Oops. I'll look into this.

**Comment by sunsided** [comment]
Heya, any updates? 🙂

**Comment by faern** [comment]
This has now been fixed in version [`0.1.2`](https://crates.io/crates/triggered/0.1.2). Stupid mistake by me. Has been fixed by replacing the `Vec<Waker>` with a `HashMap<usize, Waker>` where the `usize` is unique for each `Listener` instance. This allows each `Listener` to keep track of one single waker. At the cost of each `Listener` instance being `size_of::<usize>()` larger and each access to the `Waker` storage probably being a bit slower.
